[build-system]
requires = ["setuptools", "setuptools_scm", "wheel", "Cython"]

[tool.setuptools_scm]
root = '.'
version_scheme = 'guess-next-dev'
git_describe_command = 'git describe --tags --match sib-clustering-*.*"'

